### PR TITLE
use jquery 3.4.1

### PR DESCRIPTION
**Pull request by txm**

### CODE REVIEW

**Comment by tarikbenmerar** [comment]
Hi Andrew, sorry for not replying earlier. Thank you for jumping into the issue. I was aware of the issue before but couldn't find an appropriate solution. What I am interrested on is to have dependency on a jquery version the people wants. Should we have like two different versions for the plugin for  jquery version 2 or 3 ? or just  using on package.json ?

**Comment by txm** [comment]
Sometimes people need encouragement to upgrade :)

**Comment by tarikbenmerar** [comment]
I will merge this pull request but I will create different branches for different jquery versions so they people can still use it in their own projects. By the way, can you tell me in which context have you used the project ?

**Comment by tarikbenmerar** [comment]
@txm I have confirmed the pull request. People can still use older code with jquery 3 as there is already a migration plugin.

**Comment by txm** [comment]
Thanks @tarikbenmerar 
We use `    dataType: 'native',`

**Comment by tarikbenmerar** [comment]
ah ok @txm let's say I was curious about the data. I came across a project for smart homes if I remember well.

**Pull request merged**
